name: "Infra Preview Deploy"

on:
  push:
      branches:
      - main
      paths:
      - 10_infra/**
      - .github/workflows/infra.preview-deploy.yml
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env: 
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.2.8
  TF_PROJECT: tastylog
  TF_ENVIROMENT: dev

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      # - run: |
      #     echo "Hello world!"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      - name: Terraform format
        run: |
          terraform fmt -check
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION}}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - name: Terraform init
        run: |
          terraform init -no-color
      - name: Terraform vailidate
        run: |
          terraform validate -no-color
      - name: Terraform plan
        run: |
          terraform plan \
            -var 'project=${{ env.TF_PROJECT }}' \
            -var 'environment=${{ env.TF_ENVIROMENT }}' \
            -var 'username=${{ secrets.MYSQL_USERNNAME }}' \
            -var 'password=${{ secrets.MYSQL_PASSWORD }}' \
            -no-color \
            -input=false \
            -detailed-exitcode