name: "Slack Notify"

on:
  workflow_dispatch:
   
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notify
        uses: slackapi/slack-github-action@v2.0.0
        with:
          # v2.0.0では webhook または token が必要
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          # channel-idはここでは使えないので、payloadの中で指定
          payload: |
            {
              "channel": "C08MVSL001Z",
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Message Header",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Hello World :ghost:"
                      }
                    }
                  ]
                }
              ]
            }